blueprint:
  name: Рассвет
  description: Campanion Script to the parabolic alarm automation blueprint.
  domain: automation
  input:
    conditions:
      name: Условия
      description: Пользовательские условия запуска автоматизации
      default: []
      selector:
        condition:

    alarm_start_time:
      name: 🕒 Start Time
      description:
        Datetime helper or sensor for the alarm to start. Use time only and Workday sensor
        to determine what days to run.
      selector:
        entity:
          filter:
            - domain:
                - input_datetime
            - domain: sensor
              device_class: timestamp
          multiple: false

    offset_from_start_time:
      name: 🏁 Offset From Start Time
      description: Adjust the amount of time before or after the set Start Time value to start the transition. Enter seconds or HH:MM:SS format (e.g. "-00:05:00" to start 5 minutes before the Start Time. Useful if the start time comes from an alarm entity and you want to adjust where in the brightness cycle you are when the alarm goes off. See https://www.home-assistant.io/docs/automation/trigger/#sensors-of-datetime-device-class-with-offsets for caution about using positive offsets.
      default: "-00:00:00"
      selector:
        text:

    target_kelvin:
      description: Теплота холодного света. Это конечное значение - наиболее белое
      selector:
        color_temp:
          unit: kelvin
      default: 6500
      name: Coldest Kelvin

    start_kelvin:
      description: >-
        This is the start value. If the light is on the current value from the
        state of the light will be used and this will be ignored.
      selector:
        color_temp:
          unit: kelvin
          min: 2500
          max: 6500
      default: 2500
      name: Warmest Kelvin

    max_brightness_pct:
      description: Максимальная яркость в процентах в конце работы автоматизации
      selector:
        number:
          min: 1
          max: 100
      default: 80
      name: Максимальная яркость

    duration:
      description: Длительность работы автоматизации в минутах
      selector:
        number:
          min: 1
          max: 60
      default: 10
      name: Длительность работы


    steps_per_minute:
      description: Количество шагов изменения света в минуту
      selector:
        number:
          min: 1
          max: 12
      default: 12
      name: Шагов в минуту

    target_light:
      description: Один светильник или группа светильников
      selector:
        entity:
          filter:
            domain: light
      name: Целевой светильник

    light_timeout:
      description: Минуты, которые будет работать свет после завершения автоматизации. Значение 0 означает, что свет не будет выключен
      selector:
        number:
          min: 0
          max: 60
      default: 5
      name: Таймаут работы света
triggers:
  - trigger: time
    at:
      entity_id: !input alarm_start_time
      offset: !input offset_from_start_time
actions:
  - action: light.turn_on
    data:
      brightness_pct: "{{ min_brightness }}"
      rgb_color: "{{ [234, start_g_color, 43] }}"
      entity_id: !input target_light
mode: single